# Generated by Django 3.2.6 on 2021-08-28 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210828_0000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='remember_me',
        ),
    ]
